0920_practice/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# 명시적 상대경도를 사용, 같은 폴더내에 있으므로 '.' 으로 표시(그냥 import만 해도 되긴 함)
app_name = 'articles'
urlpatterns = [ 
    path('', views.index , name= 'index'), # 어차피 articles를 pjt urls.py가 가리키므로 생략
    path('dinner/', views.dinner , name = 'dinner'), # 주소가 길어지면 적기 힘드니 이름을 지어서 주소 대신 사용 
    path('search/', views.search , name = 'search'),
    path('throw/', views.throw , name = 'throw'),
    path('catch/', views.catch , name = 'catch'),
    path('<int:num>/', views.detail , name = 'detail'),
]

0920_practice/articles/views.py
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    context = {
        'name' : 'jane'
    }
    return render(request, 'articles/index.html', context)

def dinner(request):
    foods = ['국밥', '국수', '카레', '탕수육']
    picked = random.choice(foods)
    context = {
        'foods' : foods,
        'picked' : picked,
    }
    return render(request, 'articles/dinner.html', context)

def search(request):
    return render(request, 'articles/search.html')

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message' : message
    }
    return render(request, 'articles/catch.html', context)

def detail(request, num):
    context = {
        'num' : num
    }
    return render(request, 'articles/detail.html', context)

0920_practice/articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

0920_practice/articles/templates/articles/catch.html
{% extends 'articles/base.html' %}
{% block content %}
  <h1>Catch</h1>
  <h3>{{ message }}를 받았습니다!</h3>
{% endblock content %}

0920_practice/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <h2>{{ num }}번 게시글입니다.</h2>
</body>
</html>

0920_practice/articles/templates/articles/dinner.html
{% extends 'articles/base.html' %}
{% block content %}
  <p>{{ picked }} 메뉴는 {{ picked|length }} 글자 입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods%}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  {% if foods|length == 0 %}
    <p> 메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
{% endblock content %}





{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>{{ picked }} 메뉴는 {{ picked|length }} 글자 입니다.</p>
  <h2>메뉴판</h2>
  <ul>
    {% for food in foods%}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  {% if foods|length == 0 %}
    <p> 메뉴가 소진 되었습니다.</p>
  {% else %}
    <p>아직 메뉴가 남았습니다.</p>
  {% endif %}
</body>
</html> {% endcomment %}

0920_practice/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block content %}
  <h1>Hello, {{ name }}!</h1>

  <a href="/articles/dinner/">저녁 메뉴 확인하러 가기!!</a>
  <a href="{% url "articles:dinner" %}">저녁 메뉴 확인하러 가기!!</a>
{% endblock content %}


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Hello, {{ name }}!</h1>
</body>
</html> {% endcomment %}

0920_practice/articles/templates/articles/search.html
{% extends "articles/base.html" %}

{% block content %}
<form action="https://search.naver.com/search.naver" method="GET">
  <label for="message">검색어</label>
  <input type="text" name = "query" id = "message">
  <input type="submit" value="submit">
</form>
{% endblock content %}

0920_practice/articles/templates/articles/throw.html
{% extends 'articles/base.html' %}
{% block content %}
  <h1>Throw</h1>
  <form action="{% url "articles:catch" %}" method="GET">
    <input type="text" id = "message" name = "message">
    <input type="submit">
  </form>
{% endblock content %}