0925_class/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name = 'detail'),
    path('new/', views.new, name = 'new'), 
    path('create/', views.create, name = 'create'),
    path('<int:pk>/edit/', views.edit, name = 'edit'),
    path('<int:pk>')
]

0925_class/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

0925_class/articles/models.py
# 내장된 django 패키지 안에 db 서브패키지 안에 models.py라는 모듈을 import
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

0925_class/articles/views.py
from django.shortcuts import render
from .models import Article 

# Create your views here.

# 전체 게시글 조회(1) 후 메인 페이지 응답(2)
def index(request):
    # 1. DB에 전체 게시글을 조회
    articles = Article.objects.all()

    # 2. 전체 게시글 목록을 템플릿과 함께 응답
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# 게시글 상세 페이지를 응답하는 함수
# 해야할 일
# 1. 몇번 게시글인지 DB에 조회
# 2. 조회한 상세 게시글 데이터를 템플릿과 함께 응답
def detail(request, article_pk):
    # 1. 단일 게시글 조회
    # queryset API method ==> get()
    article = Article.objects.get(pk=article_pk) # 좌측 pk, 우측 전혀 다름 . 좌측은 모델 컬럼, 우측은 매개변수

    # 2. 단일 게시글 데이터와 템플잇을 응답
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)

# 사용자가 게시글 생성을 위한 작성 페이지를 응답하는 함수
def new(request):
    return render(request, 'articles/new.html')

# 1. 사용자로부터 입력 받은 데이터를 추출
# 2. 추출한 데이터를 DB에 저장
# 3. 저장이 완료되었다는 페이지를 응답 
def create(request):
    # 1. 
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 2. DB에 저장(3가지)
    # 2.1 
    # article = Article()
    # article.title = title 
    # article.content = content
    # article.save()

    # 2.2
    article = Article(title=title, content=content)
    article.save()
    return render(request, 'articles/create.html')
    # 2.3
    # Article.objects.create(title = title, content= content)
    # return render(request, ' articles/create.html')


def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    title = request.POST.get('title')
    contnet = request.POST.get('content')
    article.title = title
    article.content = contnet
    article.save()
    return redirect('articles:detail', article.pk)

0925_class/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>게시글이 생성 되었습니다.</h1>
</body>
</html>

0925_class/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <h2>{{ article.pk }} 번째 글</h2>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.contnet }}</p>
  <p>작성일 : {{ article.created_at }}</p>
  <p>수정일 : {{ article.updated_at }}</p>
  <hr>
  <a href="{% url "aritcles:index" %}">[메인 페이지로]</a>
</body>
</html>

0925_class/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Edit</h1> <!-- 몇번글 수정인지 알려주는 article.pk-->
  <form action="{% url "articles:update" article.pk %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="title">Title: </label>
    <input type="text" name="title" id="title" value ="{{ article.title }}">
  </div>
  <div>
    <label for="content">Content: </label>
    <textarea name="content" id="content">{{ article.content }}</textarea>
  </div>
  <input type="submit">
</form>
</body>
</html>

0925_class/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>메인 페이지</h1>
  <hr>
  {% comment %} 전체 게시글 출력 {% endcomment %}
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <a href="{% url "articles:detail" article.pk %}">글 제목: {{ article.title }}</a>
    <p>글 내용: {{ article.content }}</p>
    <hr>
  {% endfor %}
</body>
</html>

0925_class/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>New</h1>
<form action="{% url "articles:create" %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="title">Title: </label>
    <input type="text" name="title" id="title">
  </div>
  <div>
    <label for="content">Content: </label>
    <textarea name="content" id="content"></textarea>
  </div>
  <input type="submit">
</form>


  <hr>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>